name = "budgetwise-app"
compatibility_date = "2024-08-29"
pages_build_output_dir = "frontend/build"

[env.production.vars]
NODE_ENV = "production"
GENERATE_SOURCEMAP = "false"
DISABLE_ESLINT_PLUGIN = "true"

[env.preview.vars]
NODE_ENV = "development"
GENERATE_SOURCEMAP = "false"

# Cloudflare Pages Configuration (set in dashboard):
# Build command: ./build.sh
# Build output directory: frontend/build  
# Root directory: (leave blank for root)
# Node.js version: 18