name = "budgetwise-ai"
compatibility_date = "2025-10-20"
pages_build_output_dir = ".next"

[build]
command = "npm run build"

[vars]
NODE_VERSION = "22"

[env.production]
vars = { ENVIRONMENT = "production" }