name = "budgetwise"
compatibility_date = "2025-10-20"
pages_build_output_dir = "out"

[vars]
NODE_VERSION = "22"
ENVIRONMENT = "development"
# SENDGRID_API_KEY = "your_sendgrid_api_key_here"
# SENDGRID_FROM_EMAIL = "noreply@budgetwise.ai"

[env.production.vars]
ENVIRONMENT = "production"
NODE_VERSION = "22"
# SENDGRID_API_KEY = "your_sendgrid_api_key_here"
# SENDGRID_FROM_EMAIL = "noreply@budgetwise.ai"

# D1 Database Bindings
[[d1_databases]]
binding = "users"
database_name = "budgetwise-db"
database_id = "29d3d43f-8f0a-4c5c-abe9-bbe93a22414d"

[[env.production.d1_databases]]
binding = "users"
database_name = "budgetwise-db"
database_id = "29d3d43f-8f0a-4c5c-abe9-bbe93a22414d"

# R2 Bucket Bindings
[[r2_buckets]]
binding = "budgetwise_storage"
bucket_name = "budgetwise-storage"

[[env.production.r2_buckets]]
binding = "budgetwise_storage"
bucket_name = "budgetwise-storage"