name = "budgetwise"
compatibility_date = "2025-10-20"
pages_build_output_dir = "out"

[vars]
NODE_VERSION = "22"
ENVIRONMENT = "development"

[env.production.vars]
ENVIRONMENT = "production"
NODE_VERSION = "22"

# D1 Database Bindings
[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "budgetwise-db"
database_id = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" # Replace with your actual D1 database ID

# R2 Bucket Bindings
[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "budgetwise-storage"