name = "budgetwise"
compatibility_date = "2025-10-20"

[build]
command = "npm run build"

[assets]
directory = ".next/static"
base_dir = ".next"

[vars]
NODE_VERSION = "22"

[env.production]
vars = { ENVIRONMENT = "production" }