name = "budgetwise"
compatibility_date = "2025-10-20"
pages_build_output_dir = "out"

[vars]
NODE_VERSION = "22"
ENVIRONMENT = "development"

[env.production.vars]
ENVIRONMENT = "production"
NODE_VERSION = "22"