version: '3.8'

services:
  backend:
    image: node:20
    restart: always
    environment:
      - NODE_ENV=development
    ports:
      - '3001:3001'
    expose:
      - '3001'
    volumes:
      - ./:/app
    build:
      context: .
      dockerfile: budgetwise-app/Dockerfile
    user: node
    working_dir: /app
    command: npm run dev

  frontend:
    image: node:16
    restart: always
    environment:
      - NODE_ENV=development
    ports:
      - '3000:3000'
    expose:
      - '3000'
    volumes:
      - ./:/app
    build:
      context: .
      command: npm install && npm run build
    user: node
    working_dir: /app
    volumes:
      - ./:/app/dist

networks:
  budgetwise-network:
    driver: bridge
