version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - NODE_ENV=production
    ports:
      - '3001:3001'
    expose:
      - '3001'
    volumes:
      - ./server:/app/server
    working_dir: /app/server
    command: npm start

  frontend:
    build:
      context: ./client
      dockerfile: ../Dockerfile
    restart: always
    environment:
      - NODE_ENV=production
    ports:
      - '3000:3000'
    expose:
      - '3000'

networks:
  budgetwise-network:
    driver: bridge