name = "budgetwise-api"
main = "src/index.js"
compatibility_date = "2024-08-29"

[[d1_databases]]
binding = "DB"
database_name = "budgetwise"
database_id = "your-d1-database-id"

[vars]
JWT_SECRET = "your-jwt-secret-key"

[[r2_buckets]]
binding = "STORAGE"
bucket_name = "budgetwise-files"